---
version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - /opt/homeservices/nginx/data/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    restart: unless-stopped
