services:
  cAdvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    restart: always
    privileged: true
    ports:
      - "8080:8080" 
    devices:
      - /dev/kmsg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
